#ifndef NETIO_IMPL_SRC_HPP
#define NETIO_IMPL_SRC_HPP

#define NETIO_SOURCE

#include "netio/detail/config.hpp"

#if defined(NETIO_HEADER_ONLY)
# error Do not compile Netio library source with NETIO_HEADER_ONLY defined
#endif

#include "netio/impl/any_completion_executor.ipp"
#include "netio/impl/any_io_executor.ipp"
#include "netio/impl/awaitable.ipp"
#include "netio/impl/cancellation_signal.ipp"
#include "netio/impl/config.ipp"
#include "netio/impl/connect_pipe.ipp"
#include "netio/impl/error.ipp"
#include "netio/impl/error_code.ipp"
#include "netio/impl/execution_context.ipp"
#include "netio/impl/executor.ipp"
#include "netio/impl/io_context.ipp"
#include "netio/impl/multiple_exceptions.ipp"
#include "netio/impl/serial_port_base.ipp"
#include "netio/impl/system_context.ipp"
#include "netio/impl/thread_pool.ipp"
#include "netio/detail/impl/buffer_sequence_adapter.ipp"
#include "netio/detail/impl/descriptor_ops.ipp"
#include "netio/detail/impl/dev_poll_reactor.ipp"
#include "netio/detail/impl/epoll_reactor.ipp"
#include "netio/detail/impl/eventfd_select_interrupter.ipp"
#include "netio/detail/impl/handler_tracking.ipp"
#include "netio/detail/impl/io_uring_descriptor_service.ipp"
#include "netio/detail/impl/io_uring_file_service.ipp"
#include "netio/detail/impl/io_uring_socket_service_base.ipp"
#include "netio/detail/impl/io_uring_service.ipp"
#include "netio/detail/impl/kqueue_reactor.ipp"
#include "netio/detail/impl/null_event.ipp"
#include "netio/detail/impl/pipe_select_interrupter.ipp"
#include "netio/detail/impl/posix_event.ipp"
#include "netio/detail/impl/posix_mutex.ipp"
#include "netio/detail/impl/posix_serial_port_service.ipp"
#include "netio/detail/impl/posix_thread.ipp"
#include "netio/detail/impl/posix_tss_ptr.ipp"
#include "netio/detail/impl/reactive_descriptor_service.ipp"
#include "netio/detail/impl/reactive_socket_service_base.ipp"
#include "netio/detail/impl/resolver_service_base.ipp"
#include "netio/detail/impl/resolver_thread_pool.ipp"
#include "netio/detail/impl/scheduler.ipp"
#include "netio/detail/impl/select_reactor.ipp"
#include "netio/detail/impl/service_registry.ipp"
#include "netio/detail/impl/signal_set_service.ipp"
#include "netio/detail/impl/socket_ops.ipp"
#include "netio/detail/impl/socket_select_interrupter.ipp"
#include "netio/detail/impl/strand_executor_service.ipp"
#include "netio/detail/impl/strand_service.ipp"
#include "netio/detail/impl/thread_context.ipp"
#include "netio/detail/impl/throw_error.ipp"
#include "netio/detail/impl/timer_queue_set.ipp"
#include "netio/detail/impl/win_iocp_file_service.ipp"
#include "netio/detail/impl/win_iocp_handle_service.ipp"
#include "netio/detail/impl/win_iocp_io_context.ipp"
#include "netio/detail/impl/win_iocp_serial_port_service.ipp"
#include "netio/detail/impl/win_iocp_socket_service_base.ipp"
#include "netio/detail/impl/win_event.ipp"
#include "netio/detail/impl/win_mutex.ipp"
#include "netio/detail/impl/win_object_handle_service.ipp"
#include "netio/detail/impl/win_static_mutex.ipp"
#include "netio/detail/impl/win_thread.ipp"
#include "netio/detail/impl/win_tss_ptr.ipp"
#include "netio/detail/impl/winrt_ssocket_service_base.ipp"
#include "netio/detail/impl/winrt_timer_scheduler.ipp"
#include "netio/detail/impl/winsock_init.ipp"
#include "netio/execution/impl/bad_executor.ipp"
#include "netio/experimental/impl/channel_error.ipp"
#include "netio/generic/detail/impl/endpoint.ipp"
#include "netio/ip/impl/address.ipp"
#include "netio/ip/impl/address_v4.ipp"
#include "netio/ip/impl/address_v6.ipp"
#include "netio/ip/impl/host_name.ipp"
#include "netio/ip/impl/network_v4.ipp"
#include "netio/ip/impl/network_v6.ipp"
#include "netio/ip/detail/impl/endpoint.ipp"
#include "netio/local/detail/impl/endpoint.ipp"

#endif // NETIO_IMPL_SRC_HPP
