#if defined(DESKTOP_WINDOW_BUILD_WIN32_TIMER) || \
    defined(DESKTOP_WINDOW_BUILD_WIN32_MODULE) || \
    defined(DESKTOP_WINDOW_BUILD_WIN32_THREAD) || \
    defined(DESKTOP_WINDOW_BUILD_COCOA_TIMER) || \
    defined(DESKTOP_WINDOW_BUILD_POSIX_TIMER) || \
    defined(DESKTOP_WINDOW_BUILD_POSIX_MODULE) || \
    defined(DESKTOP_WINDOW_BUILD_POSIX_THREAD) || \
    defined(DESKTOP_WINDOW_BUILD_POSIX_POLL) || \
    defined(DESKTOP_WINDOW_BUILD_LINUX_JOYSTICK)
 #error "You must not define these; define zero or more _DESKTOP_WINDOW_<platform> macros instead"
#endif

#include "null_platform.h"
#define DESKTOP_WINDOW_EXPOSE_NATIVE_EGL
#define DESKTOP_WINDOW_EXPOSE_NATIVE_OSMESA

#if defined(_DESKTOP_WINDOW_WIN32)
 #include "win32_platform.h"
 #define DESKTOP_WINDOW_EXPOSE_NATIVE_WIN32
 #define DESKTOP_WINDOW_EXPOSE_NATIVE_WGL
#else
 #define DESKTOP_WINDOW_WIN32_WINDOW_STATE
 #define DESKTOP_WINDOW_WIN32_MONITOR_STATE
 #define DESKTOP_WINDOW_WIN32_CURSOR_STATE
 #define DESKTOP_WINDOW_WIN32_LIBRARY_WINDOW_STATE
 #define DESKTOP_WINDOW_WGL_CONTEXT_STATE
 #define DESKTOP_WINDOW_WGL_LIBRARY_CONTEXT_STATE
#endif

#if defined(_DESKTOP_WINDOW_COCOA)
 #include "cocoa_platform.h"
 #define DESKTOP_WINDOW_EXPOSE_NATIVE_COCOA
 #define DESKTOP_WINDOW_EXPOSE_NATIVE_NSGL
#else
 #define DESKTOP_WINDOW_COCOA_WINDOW_STATE
 #define DESKTOP_WINDOW_COCOA_MONITOR_STATE
 #define DESKTOP_WINDOW_COCOA_CURSOR_STATE
 #define DESKTOP_WINDOW_COCOA_LIBRARY_WINDOW_STATE
 #define DESKTOP_WINDOW_NSGL_CONTEXT_STATE
 #define DESKTOP_WINDOW_NSGL_LIBRARY_CONTEXT_STATE
#endif

#if defined(_DESKTOP_WINDOW_WAYLAND)
 #include "wl_platform.h"
 #define DESKTOP_WINDOW_EXPOSE_NATIVE_WAYLAND
#else
 #define DESKTOP_WINDOW_WAYLAND_WINDOW_STATE
 #define DESKTOP_WINDOW_WAYLAND_MONITOR_STATE
 #define DESKTOP_WINDOW_WAYLAND_CURSOR_STATE
 #define DESKTOP_WINDOW_WAYLAND_LIBRARY_WINDOW_STATE
#endif

#if defined(_DESKTOP_WINDOW_X11)
 #include "x11_platform.h"
 #define DESKTOP_WINDOW_EXPOSE_NATIVE_X11
 #define DESKTOP_WINDOW_EXPOSE_NATIVE_GLX
#else
 #define DESKTOP_WINDOW_X11_WINDOW_STATE
 #define DESKTOP_WINDOW_X11_MONITOR_STATE
 #define DESKTOP_WINDOW_X11_CURSOR_STATE
 #define DESKTOP_WINDOW_X11_LIBRARY_WINDOW_STATE
 #define DESKTOP_WINDOW_GLX_CONTEXT_STATE
 #define DESKTOP_WINDOW_GLX_LIBRARY_CONTEXT_STATE
#endif

#include "null_joystick.h"

#if defined(_DESKTOP_WINDOW_WIN32)
 #include "win32_joystick.h"
#else
 #define DESKTOP_WINDOW_WIN32_JOYSTICK_STATE
 #define DESKTOP_WINDOW_WIN32_LIBRARY_JOYSTICK_STATE
#endif

#if defined(_DESKTOP_WINDOW_COCOA)
 #include "cocoa_joystick.h"
#else
 #define DESKTOP_WINDOW_COCOA_JOYSTICK_STATE
 #define DESKTOP_WINDOW_COCOA_LIBRARY_JOYSTICK_STATE
#endif

#if (defined(_DESKTOP_WINDOW_X11) || defined(_DESKTOP_WINDOW_WAYLAND)) && defined(__linux__)
 #define DESKTOP_WINDOW_BUILD_LINUX_JOYSTICK
#endif

#if defined(DESKTOP_WINDOW_BUILD_LINUX_JOYSTICK)
 #include "linux_joystick.h"
#else
 #define DESKTOP_WINDOW_LINUX_JOYSTICK_STATE
 #define DESKTOP_WINDOW_LINUX_LIBRARY_JOYSTICK_STATE
#endif

#define DESKTOP_WINDOW_PLATFORM_WINDOW_STATE \
        DESKTOP_WINDOW_WIN32_WINDOW_STATE \
        DESKTOP_WINDOW_COCOA_WINDOW_STATE \
        DESKTOP_WINDOW_WAYLAND_WINDOW_STATE \
        DESKTOP_WINDOW_X11_WINDOW_STATE \
        DESKTOP_WINDOW_NULL_WINDOW_STATE \

#define DESKTOP_WINDOW_PLATFORM_MONITOR_STATE \
        DESKTOP_WINDOW_WIN32_MONITOR_STATE \
        DESKTOP_WINDOW_COCOA_MONITOR_STATE \
        DESKTOP_WINDOW_WAYLAND_MONITOR_STATE \
        DESKTOP_WINDOW_X11_MONITOR_STATE \
        DESKTOP_WINDOW_NULL_MONITOR_STATE \

#define DESKTOP_WINDOW_PLATFORM_CURSOR_STATE \
        DESKTOP_WINDOW_WIN32_CURSOR_STATE \
        DESKTOP_WINDOW_COCOA_CURSOR_STATE \
        DESKTOP_WINDOW_WAYLAND_CURSOR_STATE \
        DESKTOP_WINDOW_X11_CURSOR_STATE \
        DESKTOP_WINDOW_NULL_CURSOR_STATE \

#define DESKTOP_WINDOW_PLATFORM_JOYSTICK_STATE \
        DESKTOP_WINDOW_WIN32_JOYSTICK_STATE \
        DESKTOP_WINDOW_COCOA_JOYSTICK_STATE \
        DESKTOP_WINDOW_LINUX_JOYSTICK_STATE

#define DESKTOP_WINDOW_PLATFORM_LIBRARY_WINDOW_STATE \
        DESKTOP_WINDOW_WIN32_LIBRARY_WINDOW_STATE \
        DESKTOP_WINDOW_COCOA_LIBRARY_WINDOW_STATE \
        DESKTOP_WINDOW_WAYLAND_LIBRARY_WINDOW_STATE \
        DESKTOP_WINDOW_X11_LIBRARY_WINDOW_STATE \
        DESKTOP_WINDOW_NULL_LIBRARY_WINDOW_STATE \

#define DESKTOP_WINDOW_PLATFORM_LIBRARY_JOYSTICK_STATE \
        DESKTOP_WINDOW_WIN32_LIBRARY_JOYSTICK_STATE \
        DESKTOP_WINDOW_COCOA_LIBRARY_JOYSTICK_STATE \
        DESKTOP_WINDOW_LINUX_LIBRARY_JOYSTICK_STATE

#define DESKTOP_WINDOW_PLATFORM_CONTEXT_STATE \
        DESKTOP_WINDOW_WGL_CONTEXT_STATE \
        DESKTOP_WINDOW_NSGL_CONTEXT_STATE \
        DESKTOP_WINDOW_GLX_CONTEXT_STATE

#define DESKTOP_WINDOW_PLATFORM_LIBRARY_CONTEXT_STATE \
        DESKTOP_WINDOW_WGL_LIBRARY_CONTEXT_STATE \
        DESKTOP_WINDOW_NSGL_LIBRARY_CONTEXT_STATE \
        DESKTOP_WINDOW_GLX_LIBRARY_CONTEXT_STATE

#if defined(_WIN32)
 #define DESKTOP_WINDOW_BUILD_WIN32_THREAD
#else
 #define DESKTOP_WINDOW_BUILD_POSIX_THREAD
#endif

#if defined(DESKTOP_WINDOW_BUILD_WIN32_THREAD)
 #include "win32_thread.h"
 #define DESKTOP_WINDOW_PLATFORM_TLS_STATE    DESKTOP_WINDOW_WIN32_TLS_STATE
 #define DESKTOP_WINDOW_PLATFORM_MUTEX_STATE  DESKTOP_WINDOW_WIN32_MUTEX_STATE
#elif defined(DESKTOP_WINDOW_BUILD_POSIX_THREAD)
 #include "posix_thread.h"
 #define DESKTOP_WINDOW_PLATFORM_TLS_STATE    DESKTOP_WINDOW_POSIX_TLS_STATE
 #define DESKTOP_WINDOW_PLATFORM_MUTEX_STATE  DESKTOP_WINDOW_POSIX_MUTEX_STATE
#endif

#if defined(_WIN32)
 #define DESKTOP_WINDOW_BUILD_WIN32_TIMER
#elif defined(__APPLE__)
 #define DESKTOP_WINDOW_BUILD_COCOA_TIMER
#else
 #define DESKTOP_WINDOW_BUILD_POSIX_TIMER
#endif

#if defined(DESKTOP_WINDOW_BUILD_WIN32_TIMER)
 #include "win32_time.h"
 #define DESKTOP_WINDOW_PLATFORM_LIBRARY_TIMER_STATE  DESKTOP_WINDOW_WIN32_LIBRARY_TIMER_STATE
#elif defined(DESKTOP_WINDOW_BUILD_COCOA_TIMER)
 #include "cocoa_time.h"
 #define DESKTOP_WINDOW_PLATFORM_LIBRARY_TIMER_STATE  DESKTOP_WINDOW_COCOA_LIBRARY_TIMER_STATE
#elif defined(DESKTOP_WINDOW_BUILD_POSIX_TIMER)
 #include "posix_time.h"
 #define DESKTOP_WINDOW_PLATFORM_LIBRARY_TIMER_STATE  DESKTOP_WINDOW_POSIX_LIBRARY_TIMER_STATE
#endif

#if defined(_WIN32)
 #define DESKTOP_WINDOW_BUILD_WIN32_MODULE
#else
 #define DESKTOP_WINDOW_BUILD_POSIX_MODULE
#endif

#if defined(_DESKTOP_WINDOW_WAYLAND) || defined(_DESKTOP_WINDOW_X11)
 #define DESKTOP_WINDOW_BUILD_POSIX_POLL
#endif

